### PR TITLE
compatibility test: write with fastexcel, read with apache poi

### PR DESCRIPTION
**Pull request by rzymek**

### CODE REVIEW

**Comment by ochedru** [comment]
Thank you for your PR! There are actually some compatibility tests in `Correctness.java` where we generate a workbook with fastexcel and read it with POI after. Maybe this is an opportunity to refactor tests?

**Comment by rzymek** [comment]
Yeah, I might have missed it. `Correctness.java` is rather big.

**Comment by ochedru** [comment]
It looks like lot of tests from `Correctness` could be moved to `PoiCompatibility` for clarity.

**Comment by ochedru** [comment]
Do you agree to close this PR for now?

**Comment by rzymek** [comment]
Sure

**Pull request closed without merging**
